/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_STORAGE_FILES           8
#define MMAP_STORAGE_CHECKSUM        0x85B8

enum MMAP_STORAGE_LISTS {
    MMAP_STORAGE_ASKING_PNG = 0,        /*!< asking.png */
    MMAP_STORAGE_DONE_PNG = 1,        /*!< done.png */
    MMAP_STORAGE_ERROR_PNG = 2,        /*!< error.png */
    MMAP_STORAGE_IDLE_PNG = 3,        /*!< idle.png */
    MMAP_STORAGE_OFFLINE_PNG = 4,        /*!< offline.png */
    MMAP_STORAGE_TOOL_PNG = 5,        /*!< tool.png */
    MMAP_STORAGE_WAITING_PNG = 6,        /*!< waiting.png */
    MMAP_STORAGE_WORKING_PNG = 7,        /*!< working.png */
};
